# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\archive\LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog2(object):
    def setupUi(self, Dialog2):
        Dialog2.setObjectName("Dialog2")
        Dialog2.resize(228, 119)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog2)
        self.buttonBox.setGeometry(QtCore.QRect(-130, 80, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(Dialog2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 201, 20))
        self.lineEdit.setWhatsThis("")
        self.lineEdit.setAccessibleDescription("")
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog2)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 40, 201, 20))
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Dialog2)
        self.buttonBox.accepted.connect(Dialog2.accept)
        self.buttonBox.rejected.connect(Dialog2.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog2)

    def retranslateUi(self, Dialog2):
        _translate = QtCore.QCoreApplication.translate
        Dialog2.setWindowTitle(_translate("Dialog2", "Login"))
        self.lineEdit.setPlaceholderText(_translate("Dialog2", "login"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog2", "password"))
